### ISSUE TITLE
Provide URL for Spanish updated Kanban graphic "derivative methods" - DONE (Joseph)

### ISSUE THREAD

**Issue by CoolFede** [agilelion/Open-Kanban#16]

**Comment by agilelion** [comment]
Francisco here is the URL you need:
http://farm8.staticflickr.com/7444/12660096254_3663c7585f_o.png

Just add it to the translation file, it would look like this, I've put the link below, just view the raw code:
The nature of the Open Kanban Movement can be easily understood by examining the diagram below:
![Diagram of Open Kanban Methods - The Open Kanban Ecosystem](http://farm8.staticflickr.com/7444/12660096254_3663c7585f_o.png)

Joseph.
