### ISSUE TITLE
Eclipse Process Framework (EPF)?

### ISSUE THREAD

**Issue by westurner** [agilelion/Open-Kanban#32]
https://en.wikipedia.org/wiki/Eclipse_Process_Framework

http://epf.eclipse.org/
- http://epf.eclipse.org/wikis/scrum/
- http://epf.eclipse.org/wikis/xp/
- http://epf.eclipse.org/wikis/openup/
- http://epf.eclipse.org/wikis/epfpractices/index.htm

EPF Docs
- AFAIU, EPF Composer generates HTML which can be managed as an EPF wiki
- http://www.eclipse.org/epf/general/getting_started.php
- http://wiki.eclipse.org/EPF_Wiki_User_Guide

**Comment by westurner** [comment]
... It would be great if EPF Composer produced Responsive HTML

I don't know if EPF composer supports translation?

**Comment by westurner** [comment]
> ... It would be great if EPF Composer produced Responsive HTML

https://github.com/ostraaten/epfw (Ruby on Rails)

https://github.com/ostraaten/epfw/issues/7

> I don't know if EPF composer supports translation?

Currently, each language implementation is a separate wiki which is/should be/can be manually kept in sync.

**Comment by onknows** [comment]
EPF Composer could produce responsive HTML. There are two Eclipse plugins if I remember correctly that are responsible for the HTML generation. XSTL is used there. I think it would be possible to change those to produce different HTML for example responsive HTML.

Another option is to change EPF Wiki. As the sole developer of EPF Wiki I don't do a lot of work on it anymore. Beginning this year is last time I created a new release that integrates Sphinx search engine. The search pages use a bit of Bootstrap, JQuery.

EPF Wiki is dated. It was created in 2006/7. IMHO needs a complete overhaul. Too much work for a single sole developer.

**Comment by westurner** [comment]
Thanks!

Where is the source for EPF Composer?

[EDIT]

http://www.eclipse.org/epf/composer_dev_guide/cvs_setup.php

TIL about http://cvs2svn.tigris.org/cvs2git.html

**Comment by joseph-hurtado** [comment]
Interesting stuff folks, but no connection that I can see with Open Kanban.

**Comment by westurner** [comment]
EPF is a great resource for Software Project Management process documentation.

It would be great to see http://epf.eclipse.org/wikis/[open]kanban/

An Open Kanban EPF wiki could be created with EPF Composer.

Otherwise, https://en.wikipedia.org/wiki/Kanban_(development) was a great resource.
